# Generated by go2rpm 1
%bcond_without check

# https://github.com/rolieup/golie
%global goipath         github.com/rolieup/golie
%global commit          9dd93d88181d5c73097761848231426343a01667

%gometa

%global common_description %{expand:
A client/server implementation of ROLIE written in GO.}

%global golicenses      LICENSE LICENSE.NIST
%global godocs          examples README.md

Name:           golie
Version:        0
Release:        0.1%{?dist}
Summary:        A client/server implementation of ROLIE written in GO

# Upstream license specification: CC0-1.0
License:        CC0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/gocomply/scap/pkg/scap/constants)
BuildRequires:  golang(github.com/gocomply/scap/pkg/scap/scap_document)
BuildRequires:  golang(github.com/sirupsen/logrus)
BuildRequires:  golang(github.com/spf13/cobra)

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE LICENSE.NIST
%doc examples README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Thu Jul 02 19:38:12 CEST 2020 Šimon Lukašík <slukasik@redhat.com> - 0-0.1.20200702git9dd93d8
- Initial package

