# Generated by go2rpm 1
%bcond_without check

# https://github.com/gocomply/scap
%global goipath         github.com/gocomply/scap
%global commit          27dcc4e20641d934c885afd57b1ccd0e20e0cb5c

%gometa

%global common_description %{expand:
A GO module of the Security Content Automation Protocol (SCAP) Specification.}

%global golicenses      LICENSE
%global godocs          examples README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        A GO module of the Security Content Automation Protocol (SCAP) Specification

# Upstream license specification: CC0-1.0
License:        CC0
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Thu Jul 02 18:27:06 CEST 2020 Šimon Lukašík <slukasik@redhat.com> - 0-0.1.20200702git27dcc4e
- Initial package

